# Generated by Django 5.1.3 on 2024-11-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_restroom_current_occupancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='restroom',
            name='floor',
            field=models.PositiveIntegerField(default=1, help_text='Этаж, начиная с 1'),
        ),
        migrations.AddField(
            model_name='restroom',
            name='status',
            field=models.BooleanField(default=True, help_text='True - красный, False - зеленый'),
        ),
        migrations.AlterField(
            model_name='restroom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
